trigger:
    - master

resources :
    repositories:
    - repository: pipelines
      type: git
      name: pipelines-template
    - repository: manifests
      type: git
      name: kustomize-template

name: v$(Date:yyyyMMdd)$(Rev:.r)

variables:
    REGISTRY_CONNECTION_NAME: myacr
    IMAGE_NAME: apps/hello
    registry_uri: jbtestacr.azurecr.io
    application_name: hello
    ENVIRONMENT_NAME: Dev

stages:
    - stage: Java_App_Build
      displayName: Java application Build
      jobs:
        - job: build
          displayName: Maven build, docker build and tagging on git
          pool:
            vmImage: ubuntu-latest
          variables:
            MAVEN_CACHE_FOLDER: $(System.DefaultWorkingDirectory)/.m2/repository
            MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
            JDK_VERSION: '11'
          steps:
            - template: build.yaml@pipelines
    - stage: AKS_Deploy_Dev
      displayName: AKS Deploy on Development
      dependsOn: Java_App_Build
      jobs:
        - deployment: Deploy on Deployment
          displayName: Deploy on Development
          pool:
            vmImage: ubuntu-lastest
          environment: $(ENVIRONMENT_NAME).$(APPLICATION_NAME)
          variables:
            KUSTOMIZATION_PATH: './$(APPLICATION_NAME)/dev'
          strategy:
            runOnce:
              deploy:
                steps:
                  - template: deploy.yaml@pipelines